"""Add advanced voice profile fields

Revision ID: ff52d08b375b
Revises: b355c2f99eca
Create Date: 2026-06-25 15:44:44.170828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff52d08b375b'
down_revision: Union[str, Sequence[str], None] = 'b355c2f99eca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('formatting_style', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('vocabulary_rules', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('content_pillars', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('example_posts', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'example_posts')
    op.drop_column('users', 'content_pillars')
    op.drop_column('users', 'vocabulary_rules')
    op.drop_column('users', 'formatting_style')
    # ### end Alembic commands ###
